NDP.registerManifest({
  id: 'switchboard',
  title: '418 Linden',
  blurb: 'Operator. Five nights. Route the calls.',
  description: 'A 1920s telephone operator at the 418 Linden exchange. Calls come in. The calls are wrong. Route each caller to the right destination; listen in if you dare. Five nights. Three endings.',
  controls: 'Click a lit lamp to answer. Drag a jack onto the caller\'s line, drag the other jack onto the destination line. Hold [L] to listen. [D] deny a call. ESC pause.',
  theme: { bg: '#14090a', accent: '#c7a35a', accent2: '#d84a48' },

  /* Voice samples are generated by scripts/generate-voices.js. If they're
     missing, the runtime uses SpeechSynthesis which sounds appropriately
     uncanny for this game. All other assets are procedural. */
  assets: [],

  previewDraw(ctx, t, w, h) {
    // Wooden panel
    const grd = ctx.createLinearGradient(0, 0, 0, h);
    grd.addColorStop(0, '#2a1a0e'); grd.addColorStop(1, '#17100a');
    ctx.fillStyle = grd; ctx.fillRect(0, 0, w, h);

    // Switchboard sockets — 2 rows
    for (let row = 0; row < 2; row++) {
      for (let i = 0; i < 8; i++) {
        const x = 20 + i * ((w - 40) / 7);
        const y = row === 0 ? h * 0.28 : h * 0.6;
        ctx.fillStyle = '#0a0604';
        ctx.beginPath(); ctx.arc(x, y, 7, 0, Math.PI * 2); ctx.fill();
        ctx.strokeStyle = '#6a4a20'; ctx.lineWidth = 1;
        ctx.beginPath(); ctx.arc(x, y, 7, 0, Math.PI * 2); ctx.stroke();
        // Ringing lamp above
        const ringing = ((i + Math.floor(t * 0.9)) % 5) === 0 && row === 0;
        if (ringing) {
          const pulse = 0.7 + Math.sin(t * 10 + i) * 0.3;
          ctx.fillStyle = 'rgba(255,204,51,' + pulse + ')';
          ctx.beginPath(); ctx.arc(x, y - 14, 3, 0, Math.PI * 2); ctx.fill();
        }
      }
    }

    // A couple of patch cables
    for (let i = 0; i < 2; i++) {
      const ax = 30 + (i * 2) * ((w - 40) / 7);
      const bx = 30 + (i * 2 + 3) * ((w - 40) / 7);
      const ay = h * 0.28, by = h * 0.6;
      ctx.strokeStyle = i === 0 ? '#d84a48' : '#c7a35a';
      ctx.lineWidth = 2; ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(ax, ay);
      ctx.quadraticCurveTo((ax + bx) / 2, h * 0.85, bx, by);
      ctx.stroke();
      ctx.fillStyle = '#e2ca7a';
      ctx.beginPath(); ctx.arc(ax, ay, 4, 0, Math.PI * 2); ctx.fill();
      ctx.beginPath(); ctx.arc(bx, by, 4, 0, Math.PI * 2); ctx.fill();
    }

    // Text hint
    ctx.fillStyle = '#c7a35a';
    ctx.font = 'bold 11px ui-monospace, monospace';
    ctx.textAlign = 'center';
    ctx.fillText('418 LINDEN EXCHANGE', w / 2, h - 12);
    // Flicker
    if ((Math.sin(t * 3) > 0.92)) {
      ctx.fillStyle = 'rgba(216,74,72,0.3)';
      ctx.fillRect(0, 0, w, h);
    }
  }
});
